#!/usr/bin/python

import csv
import sys
import re
import os.path

filepath = os.path.dirname(sys.argv[1])
filename = os.path.basename(sys.argv[1])
with open(sys.argv[1], 'rb') as csvFile , open(filepath + '/reformated-'+ filename, 'wb') as outputFile:
    readObject = csv.reader(csvFile, delimiter=',')
    outputWriter = csv.writer(outputFile, delimiter=',')

    for row in readObject:
        for item in row:
            if item == 'null':
                item = ''

        outputWriter.writerow(row)


